"use client";

import { useActionState } from "react";
import { useFormStatus } from "react-dom";
import { uploadEventFile, setEventFileLabel, deleteEventFile } from "@/app/(app)/events/actions";

export type EventFileRow = {
  id: string;
  name: string;
  created_at: string;
  size_bytes: number | null;
  source: string;
  label_id: string | null;
  url?: string;
};
type Label = { id: string; name: string };

function humanSize(bytes: number | null): string {
  if (!bytes) return "";
  const mb = bytes / (1024 * 1024);
  return mb >= 1 ? `${mb.toFixed(1)} MB` : `${(bytes / 1024).toFixed(0)} KB`;
}

function UploadButton() {
  const { pending } = useFormStatus();
  return (
    <button type="submit" disabled={pending} className="btn-primary px-4 py-2 text-sm disabled:opacity-60">
      {pending ? "Uploading…" : "Upload"}
    </button>
  );
}

/* Staff Files section on the event Documents tab: upload any file (music, photos,
   PDFs…), give it a label, and remove it. Labels drive the <document_LABEL> email
   attach tag. */
export default function EventFilesSection({
  eventId,
  files,
  labels,
}: {
  eventId: string;
  files: EventFileRow[];
  labels: Label[];
}) {
  const [state, action] = useActionState(uploadEventFile.bind(null, eventId), null as { ok: boolean; error?: string } | null);

  const labelName = (id: string | null) => (id ? labels.find((l) => l.id === id)?.name ?? null : null);

  return (
    <div>
      <h2 className="card-title">Files</h2>

      <form action={action} className="mb-3 flex flex-wrap items-center gap-2 rounded-xl border border-dashed border-zinc-300 p-3 dark:border-white/15">
        <input
          type="file"
          name="file"
          required
          className="max-w-[16rem] text-sm text-zinc-600 file:mr-3 file:rounded-lg file:border-0 file:bg-brand/10 file:px-3 file:py-1.5 file:text-sm file:font-semibold file:text-brand dark:text-zinc-300"
        />
        <select name="label_id" defaultValue="" className="input w-40" title="Label (optional)">
          <option value="">No label</option>
          {labels.map((l) => (
            <option key={l.id} value={l.id}>{l.name}</option>
          ))}
        </select>
        <UploadButton />
        <span className="text-[11px] text-zinc-400">Music, photos, PDFs — up to 50 MB.</span>
      </form>
      {state && !state.ok && state.error && (
        <p className="mb-3 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700 dark:bg-red-500/10 dark:text-red-300">{state.error}</p>
      )}

      <div className="card overflow-hidden">
        {files.map((f) => (
          <div key={f.id} className="flex items-center gap-3 border-t border-zinc-100 px-4 py-2.5 first:border-t-0 dark:border-white/[0.05]">
            <span className="text-lg">📎</span>
            <div className="min-w-0 flex-1">
              <a href={f.url ?? "#"} target="_blank" rel="noopener noreferrer" className="truncate text-sm font-semibold text-brand hover:underline dark:text-brand-lighter">
                {f.name}
              </a>
              <div className="text-[11px] text-zinc-400">
                {new Date(f.created_at).toLocaleString()}
                {f.size_bytes ? ` · ${humanSize(f.size_bytes)}` : ""}
                {f.source === "generated" ? " · generated by XOS" : ""}
                {labelName(f.label_id) ? ` · 🏷 ${labelName(f.label_id)}` : ""}
              </div>
            </div>

            <form action={setEventFileLabel.bind(null, eventId, f.id)}>
              <select
                name="label_id"
                defaultValue={f.label_id ?? ""}
                onChange={(e) => e.currentTarget.form?.requestSubmit()}
                className="input py-1 text-xs"
                title="Set label"
              >
                <option value="">No label</option>
                {labels.map((l) => (
                  <option key={l.id} value={l.id}>{l.name}</option>
                ))}
              </select>
            </form>

            <form action={deleteEventFile.bind(null, eventId, f.id)}>
              <button type="submit" title="Remove file" className="rounded px-2 py-1 text-sm text-zinc-400 hover:bg-red-50 hover:text-red-600 dark:hover:bg-red-500/10">
                ✕
              </button>
            </form>
          </div>
        ))}
        {files.length === 0 && (
          <p className="px-4 py-6 text-center text-sm text-zinc-500">
            No files yet. Upload music, photos, or documents above — or PDFs from outgoing emails are saved here automatically.
          </p>
        )}
      </div>
    </div>
  );
}
