"use client";

import { useState } from "react";
import {
  renderSignatureHtml,
  normalizeSignatureConfig,
  type SignatureConfig,
} from "@/lib/emailSignature";

/* Structured email-signature builder. Emits the config as JSON in a hidden field
   (name="email_signature_config") for the saveEmailSignature action, and shows a
   live preview generated by the same renderSignatureHtml the server persists. */

function Switch({
  label,
  checked,
  onChange,
}: {
  label: string;
  checked: boolean;
  onChange: (v: boolean) => void;
}) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      aria-label={label}
      onClick={() => onChange(!checked)}
      className={`relative h-5 w-9 shrink-0 rounded-full transition ${checked ? "bg-brand" : "bg-zinc-300 dark:bg-white/15"}`}
    >
      <span className={`absolute top-0.5 h-4 w-4 rounded-full bg-white transition-all ${checked ? "left-4" : "left-0.5"}`} />
    </button>
  );
}

function Seg<T extends string>({
  value,
  onChange,
  options,
}: {
  value: T;
  onChange: (v: T) => void;
  options: [T, string][];
}) {
  return (
    <div className="inline-flex overflow-hidden rounded-md border border-zinc-300 dark:border-white/15">
      {options.map(([v, l]) => (
        <button
          key={v}
          type="button"
          onClick={() => onChange(v)}
          className={`px-3 py-1 text-xs transition ${
            value === v ? "bg-brand text-white" : "bg-white text-zinc-600 hover:bg-zinc-50 dark:bg-white/[0.06] dark:text-zinc-300 dark:hover:bg-white/10"
          }`}
        >
          {l}
        </button>
      ))}
    </div>
  );
}

const rowClass = "flex items-center justify-between gap-3 py-2.5 border-b border-zinc-100 dark:border-white/[0.06]";
const rowLabel = "text-sm text-zinc-700 dark:text-zinc-200";

export default function SignatureBuilder({ initial }: { initial?: unknown }) {
  const [cfg, setCfg] = useState<SignatureConfig>(() => normalizeSignatureConfig(initial));
  const [mode, setMode] = useState<"light" | "dark">("light");

  function set<K extends keyof SignatureConfig>(key: K, val: SignatureConfig[K]) {
    setCfg((c) => ({ ...c, [key]: val }));
  }

  // Render with baked-in colors for the chosen preview mode; the stored email
  // HTML (generated server-side) uses a media query for real dark-mode inboxes.
  const previewHtml = renderSignatureHtml(cfg, mode === "dark" ? "previewDark" : "previewLight");

  return (
    <div>
      <input type="hidden" name="email_signature_config" value={JSON.stringify(cfg)} />

      <div className="grid gap-5 lg:grid-cols-2">
        {/* Controls */}
        <div>
          <div className={rowClass}>
            <span className={rowLabel}>Logo size</span>
            <Seg value={cfg.logoSize} onChange={(v) => set("logoSize", v)} options={[["s", "S"], ["m", "M"], ["l", "L"]]} />
          </div>
          <div className={rowClass}>
            <span className={rowLabel}>Alignment</span>
            <Seg value={cfg.align} onChange={(v) => set("align", v)} options={[["left", "Left"], ["center", "Center"]]} />
          </div>
          <div className={rowClass}>
            <span className={rowLabel}>Divider line</span>
            <Switch label="Divider line" checked={cfg.divider} onChange={(v) => set("divider", v)} />
          </div>

          <div className="py-2.5 border-b border-zinc-100 dark:border-white/[0.06]">
            <div className="flex items-center justify-between gap-3">
              <span className={rowLabel}>Website</span>
              <Switch label="Website" checked={cfg.showWebsite} onChange={(v) => set("showWebsite", v)} />
            </div>
            {cfg.showWebsite && (
              <input className="input mt-2 w-full" value={cfg.website} onChange={(e) => set("website", e.target.value)} placeholder="xpressdjs.com" />
            )}
          </div>

          <div className="py-2.5 border-b border-zinc-100 dark:border-white/[0.06]">
            <div className="flex items-center justify-between gap-3">
              <span className={rowLabel}>Email address</span>
              <Switch label="Email address" checked={cfg.showEmail} onChange={(v) => set("showEmail", v)} />
            </div>
            {cfg.showEmail && (
              <input className="input mt-2 w-full" value={cfg.email} onChange={(e) => set("email", e.target.value)} placeholder="events@xpressdjs.com" />
            )}
          </div>

          <div className="py-2.5 border-b border-zinc-100 dark:border-white/[0.06]">
            <div className="flex items-center justify-between gap-3">
              <span className={rowLabel}>Phone</span>
              <Switch label="Phone" checked={cfg.showPhone} onChange={(v) => set("showPhone", v)} />
            </div>
            {cfg.showPhone && (
              <input className="input mt-2 w-full" value={cfg.phone} onChange={(e) => set("phone", e.target.value)} placeholder="(555) 123-4567" />
            )}
          </div>

          <div className="py-2.5">
            <div className="flex items-center justify-between gap-3">
              <span className={rowLabel}>Social links</span>
              <Switch label="Social links" checked={cfg.showSocial} onChange={(v) => set("showSocial", v)} />
            </div>
            {cfg.showSocial && (
              <div className="mt-2 space-y-2">
                <input className="input w-full" value={cfg.instagram} onChange={(e) => set("instagram", e.target.value)} placeholder="instagram.com/xpressdjs" />
                <input className="input w-full" value={cfg.tiktok} onChange={(e) => set("tiktok", e.target.value)} placeholder="tiktok.com/@xpressdjs" />
              </div>
            )}
          </div>
        </div>

        {/* Live preview */}
        <div>
          <div className="mb-2 flex items-center justify-between">
            <span className="text-xs text-zinc-500">Live preview</span>
            <Seg value={mode} onChange={setMode} options={[["light", "Light"], ["dark", "Dark"]]} />
          </div>
          <div className="rounded-xl p-5 transition-colors" style={{ background: mode === "dark" ? "#1c1a24" : "#f4f2fa" }}>
            <div className="rounded-xl p-5 transition-colors" style={{ background: mode === "dark" ? "#26232f" : "#ffffff" }}>
              <div className="text-xs" style={{ color: mode === "dark" ? "#8a8a94" : "#9a9aa2" }}>
                …email body ends here.
              </div>
              {/* Preview of the generated signature; escaped/controlled HTML from renderSignatureHtml. */}
              <div dangerouslySetInnerHTML={{ __html: previewHtml }} />
            </div>
          </div>
          <p className="mt-2 text-xs text-zinc-500">
            Toggle the preview to Dark to see the logo swap to the white version — it never disappears on a dark background.
          </p>
        </div>
      </div>
    </div>
  );
}
