-- XOS — notification mailbox (top nav bar bell).
-- Notifications are generated by database triggers so they fire no matter how the
-- underlying change happens (UI, booking helper, webhook, cron). The General
-- settings notif_types list controls which types get created; notif_sound controls
-- the alert sound in the top bar.

create table if not exists notifications (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  title text not null,
  body text,
  href text,                      -- where clicking the notification takes you
  created_at timestamptz not null default now(),
  read_at timestamptz
);
create index if not exists notifications_unread_idx on notifications(created_at desc) where read_at is null;

alter table notifications enable row level security;
do $$ begin
  create policy "authenticated full access" on notifications
    for all to authenticated using (true) with check (true);
exception when duplicate_object then null;
end $$;

-- central creator — respects the General settings notif_types allowlist
create or replace function create_notification(p_type text, p_title text, p_body text, p_href text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare enabled text[];
begin
  select notif_types into enabled from company_settings where id = true;
  if enabled is null or p_type = any (enabled) then
    insert into notifications (type, title, body, href) values (p_type, p_title, p_body, p_href);
  end if;
end;
$$;

-- ============ GENERATORS ============

-- payments: New Payment Received / Unassigned Pending Payments
create or replace function notify_payment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare ev_name text;
begin
  if new.event_id is not null then
    select coalesce(nullif(name, ''), '(unnamed event)') into ev_name from events where id = new.event_id;
    perform create_notification(
      'new_payment_received',
      format('Payment received — $%s', to_char(new.amount, 'FM999,999,990.00')),
      format('%s · %s', coalesce(ev_name, 'event'), new.method),
      '/events/' || new.event_id
    );
  else
    perform create_notification(
      'unassigned_pending_payments',
      format('Unassigned payment — $%s', to_char(new.amount, 'FM999,999,990.00')),
      'Not linked to an event yet — assign it.',
      '/payments'
    );
  end if;
  return new;
end;
$$;

drop trigger if exists payments_notify on payments;
create trigger payments_notify
  after insert on payments
  for each row execute function notify_payment();

-- time off requests
create or replace function notify_time_off()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare emp_name text;
begin
  if new.status = 'pending' then
    select first_name || ' ' || last_name into emp_name from employees where id = new.employee_id;
    perform create_notification(
      'time_off_requests',
      format('Time off request — %s', coalesce(emp_name, 'employee')),
      format('%s → %s', new.start_date, new.end_date),
      '/employees/' || new.employee_id
    );
  end if;
  return new;
end;
$$;

drop trigger if exists time_off_notify on employee_time_off;
create trigger time_off_notify
  after insert on employee_time_off
  for each row execute function notify_time_off();

-- bounced / complained emails (status widened by migration 00023)
create or replace function notify_email_bounce()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status in ('bounced', 'complained') and new.status is distinct from old.status then
    perform create_notification(
      'email_bounced',
      format('Email %s — %s', new.status, new.to_address),
      new.subject,
      case when new.event_id is not null then '/events/' || new.event_id else '/settings/email' end
    );
  end if;
  return new;
end;
$$;

drop trigger if exists email_log_notify on email_log;
create trigger email_log_notify
  after update on email_log
  for each row execute function notify_email_bounce();

-- include the new type in the default allowlist
update company_settings
set notif_types = array_append(notif_types, 'email_bounced')
where id = true and not ('email_bounced' = any (notif_types));
