-- Seed the "Venue Partner Agreement" contract template (the no-payment Event
-- Services Agreement for events booked through a venue), and wire it — plus the
-- HighLevel onboarding-calendar embed — to the Venue Partner journey.
--
-- Built with jsonb_build_object per block so the legal prose needs no JSON
-- escaping. Section 1 auto-fills from the event via merge tags; overtime uses
-- <overtime_rate>; the media-release opt-out is captured at signing (photo_release).

do $mig$
declare v_tpl uuid;
begin
  if exists (select 1 from document_templates where name = 'Venue Partner Agreement') then
    return;
  end if;

  insert into document_templates (name, doc_type, photo_release, is_active, blocks)
  values ('Venue Partner Agreement', 'contract', true, true,
    jsonb_build_array(
      jsonb_build_object('id','intro','type','text','html', $h$<p style="text-align:center"><strong>XPRESS ENTERTAINMENT CORP</strong><br>11280 Pines Blvd, Pembroke Pines, FL 33026</p><p style="text-align:center"><strong>EVENT SERVICES AGREEMENT &amp; CLIENT ACKNOWLEDGMENT</strong><br><em>For Events Booked Through a Venue</em></p><p>This Event Services Agreement &amp; Client Acknowledgment (this “Agreement”) is entered into as of the date of the last signature below, by and between <strong>Xpress Entertainment Corp</strong>, a Florida corporation with its principal place of business at 11280 Pines Blvd, Pembroke Pines, FL 33026 (the “Company,” “we,” or “us”), and the undersigned client(s) identified in Section 1 below (individually and collectively, the “Client,” “you,” or “your”). If more than one person signs as Client, each is jointly and severally bound by this Agreement.</p><p><strong>Background.</strong> You have contracted with the venue identified in Section 1 (the “Venue”) to host your event (the “Event”). The Venue — not you — has engaged the Company as a vendor to provide entertainment services for the Event under a separate agreement between the Company and the Venue (the “Venue Agreement”), and the fees for the Company’s standard services are payable to the Company by the Venue. This Agreement does not require you to pay the Company for those standard services. Its purpose is to establish the terms of the direct relationship between you and the Company regarding the performance of the services, planning and expectations, conduct at the Event, and the allocation of risk and responsibility between us.$h$),
      jsonb_build_object('id','s1','type','section','title','1. Event Details','html', $h$<p>The following describes the Event. If any detail conflicts with the Venue’s final Event Order, the final Event Order controls.</p><p><strong>Client Name(s):</strong> &lt;client_name&gt;<br><strong>Event Date:</strong> &lt;event_date_long&gt;<br><strong>Event Type:</strong> &lt;event_type&gt;<br><strong>Venue:</strong> &lt;venue_name&gt;<br><strong>Venue Address:</strong> &lt;venue_address&gt;<br><strong>Performance Start / End:</strong> &lt;start_time&gt; – &lt;end_time&gt;<br><strong>Services / Package:</strong> As set forth in the Venue’s banquet event order or purchase order (the “Event Order”).<br><strong>Add-Ons (billed directly):</strong> As separately confirmed with the Company.</p>$h$),
      jsonb_build_object('id','s2','type','section','title','2. Engagement Through the Venue; Scope of Services','html', $h$<p>The Company’s services for the Event are limited to those set forth in the Event Order confirmed between the Company and the Venue. Requests to change, add to, or expand the services (including hours, equipment, or staffing) must be made through the Venue, except add-ons purchased directly from the Company under Section 4. The Company has no obligation to provide any service not confirmed in the Event Order or in a signed writing with the Company. Nothing in this Agreement obligates you to pay the Company for the standard services covered by the Event Order.</p>$h$),
      jsonb_build_object('id','s3','type','section','title','3. Planning; Music Selections; Timeline','html', $h$<p>You agree to provide the Company with final music selections, any “do not play” list, key announcements (including correct name spellings and pronunciations), and the final Event timeline no later than fourteen (14) days before the Event Date. The Company will perform in accordance with the final written timeline provided to it. The Company will use reasonable efforts to accommodate day-of requests and changes, but such requests are accommodated at the Company’s reasonable discretion and subject to Venue rules and time constraints. The Company is entitled to rely on the accuracy and completeness of information you provide and is not responsible for errors resulting from inaccurate or late information.</p>$h$),
      jsonb_build_object('id','s4','type','section','title','4. Payment; Add-Ons; Overtime','html', $h$<p>Fees for the Company’s standard services are invoiced to and payable by the Venue under the Venue Agreement. Any additional products or services purchased by you directly from the Company (for example, additional performance hours, enhanced lighting, photo booth, or special effects) (“Add-Ons”) require a separate written confirmation signed or electronically accepted by you and the Company, stating the price and payment terms. Requests to extend the performance beyond the scheduled end time are subject to the Company’s availability, the Venue’s permission, and applicable noise ordinances and curfews, and are billed at a rate of $&lt;overtime_rate&gt; per hour or portion thereof, payable no later than the conclusion of the Event unless otherwise agreed in writing.</p>$h$),
      jsonb_build_object('id','s5','type','section','title','5. Venue Rules; Legal Restrictions on Sound','html', $h$<p>The Company is contractually required to comply with the Venue’s policies and with applicable law, which may include speaker placement and orientation requirements, sound-level limits, mandatory music cutoff times (for example, county noise ordinances), and the Venue’s right to reduce volume or disconnect power to the sound system. You acknowledge and agree that the Company’s compliance with any such rule, instruction, ordinance, or directive of the Venue or a governmental authority — including any resulting interruption, reduction, or early termination of the performance — is not a breach of this Agreement and will not give rise to any claim against or liability of the Company.</p>$h$),
      jsonb_build_object('id','s6','type','section','title','6. Power, Setup, and Site Conditions','html', $h$<p>The Company’s performance requires (a) adequate and safely functioning electrical power reasonably suitable for professional audio equipment; (b) a level, dry, and safe setup area; and (c) for outdoor performances, overhead cover and reasonable protection of the equipment from rain, wind, and extreme conditions. You are responsible for coordinating with the Venue to ensure these conditions are met. The Company may delay, pause, or suspend the performance if, in its reasonable judgment, site or weather conditions pose a risk to persons or equipment, and may resume when the risk is resolved. The Company is not liable for any interruption or non-performance to the extent caused by inadequate power, unsafe site conditions, or weather.</p>$h$),
      jsonb_build_object('id','s7','type','section','title','7. Conduct; Care of Equipment; Damage by Guests','html', $h$<p>Only the Company’s personnel may operate or handle the Company’s equipment. You are responsible for loss of or damage to the Company’s equipment caused by you or your guests, invitees, or other vendors engaged by you, in the amount of the reasonable cost of repair or replacement, payable within fifteen (15) days of the Company’s written invoice. The Company may pause the performance if its personnel are subjected to violent, threatening, abusive, or unsafe behavior, and will resume once the situation is reasonably resolved; any such pause is not a breach of this Agreement.</p>$h$),
      jsonb_build_object('id','s8','type','section','title','8. Personnel; Substitution','html', $h$<p>The Company will assign a qualified, professional DJ and any supporting staff for the Event. In the case of illness, emergency, or other circumstances beyond the Company’s reasonable control, the Company may substitute a comparably qualified professional, and will notify the Venue and, where practicable, you. Performance by a substitute in accordance with this Agreement fulfills the Company’s obligations.</p>$h$),
      jsonb_build_object('id','s9','type','section','title','9. Cancellation; Postponement; Rescheduling','html', $h$<p>Because the Event and the Company’s engagement are booked through the Venue, any cancellation, postponement, or rescheduling of the Event — and any associated fees, credits, or refunds — are governed exclusively by your contract with the Venue and by the Venue Agreement. The Company is not a party to your contract with the Venue, has no control over and no responsibility for the Venue’s decisions, and has no obligation to refund or credit amounts you paid to the Venue. If the Event is rescheduled, the Company’s services on the new date are subject to the Company’s availability; if the Company is unavailable, its obligations for the Event end without liability to you.</p>$h$),
      jsonb_build_object('id','s10','type','section','title','10. Force Majeure','html', $h$<p>Neither you nor the Company is liable for a failure or delay in performance caused by circumstances beyond the affected party’s reasonable control, including acts of God, hurricane, flood, fire, epidemic or public-health emergency, governmental order, civil unrest, utility failure, or labor disturbance (a “Force Majeure Event”). The affected party will notify the other promptly and use reasonable efforts to mitigate. This Section does not excuse payment obligations for Add-Ons already provided.</p>$h$),
      jsonb_build_object('id','s11','type','section','title','11. Media Release','html', $h$<p>You grant the Company permission to photograph and record portions of the Event (including images of you and your guests) and to use such media in the Company’s portfolio, website, social media, and other marketing materials, without compensation. The Company will use such media tastefully and professionally, will not state or imply your endorsement of any third-party product, and will not sell your images to unrelated third parties. This release survives the Event.</p><p><em>If you wish to decline this media release, you may opt out using the checkbox when you sign below; your choice is recorded on the signed Agreement.</em></p>$h$),
      jsonb_build_object('id','s12','type','section','title','12. Limitation of Liability','html', $h$<p>TO THE MAXIMUM EXTENT PERMITTED BY LAW: (A) THE COMPANY WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR DAMAGES FOR EMOTIONAL DISTRESS, LOSS OF ENJOYMENT, OR LOSS OF MEMORIES OR OPPORTUNITY, ARISING OUT OF OR RELATING TO THIS AGREEMENT OR THE EVENT, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; (B) THE COMPANY’S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THIS AGREEMENT OR THE EVENT WILL NOT EXCEED THE GREATER OF (i) THE AMOUNTS ACTUALLY PAID BY YOU DIRECTLY TO THE COMPANY FOR THE EVENT, OR (ii) THE AMOUNT PAID OR PAYABLE BY THE VENUE TO THE COMPANY THAT IS ALLOCABLE TO THE EVENT; AND (C) THE COMPANY IS NOT RESPONSIBLE FOR THE ACTS OR OMISSIONS OF THE VENUE, OTHER VENDORS, OR EVENT GUESTS. Nothing in this Agreement limits or excludes liability that cannot be limited or excluded under applicable law, including liability arising from a party’s gross negligence or willful misconduct.</p>$h$),
      jsonb_build_object('id','s13','type','section','title','13. Indemnification by Client','html', $h$<p>You will indemnify, defend, and hold harmless the Company and its officers, employees, and contractors from and against third-party claims, damages, liabilities, costs, and reasonable attorneys’ fees arising out of (a) the acts or omissions of you or your guests, invitees, or other vendors engaged by you; (b) content, materials, or instructions you provide to the Company (including requested content); or (c) your breach of this Agreement — in each case except to the extent caused by the Company’s negligence or willful misconduct.</p>$h$),
      jsonb_build_object('id','s14','type','section','title','14. Relationship of the Parties','html', $h$<p>The Company is an independent vendor engaged by the Venue. The Company is not the agent, employee, partner, or representative of the Venue, and nothing in this Agreement creates any agency, partnership, or joint venture. This Agreement does not amend, and is not intended to conflict with, your contract with the Venue or the Venue Agreement; it governs only the direct relationship between you and the Company. There are no third-party beneficiaries of this Agreement.</p>$h$),
      jsonb_build_object('id','s15','type','section','title','15. Governing Law; Dispute Resolution; Attorneys’ Fees','html', $h$<p>This Agreement is governed by the laws of the State of Florida, without regard to conflict-of-laws principles. The parties will first attempt in good faith to resolve any dispute arising out of or relating to this Agreement or the Event through direct discussion for a period of thirty (30) days after written notice of the dispute. Any dispute not so resolved shall be brought exclusively in the state courts located in Broward County, Florida, and each party irrevocably consents to the jurisdiction and venue of such courts. EACH PARTY KNOWINGLY, VOLUNTARILY, AND IRREVOCABLY WAIVES ANY RIGHT TO TRIAL BY JURY IN ANY PROCEEDING ARISING OUT OF OR RELATING TO THIS AGREEMENT OR THE EVENT. The prevailing party in any proceeding is entitled to recover its reasonable attorneys’ fees and costs.</p>$h$),
      jsonb_build_object('id','s16','type','section','title','16. Miscellaneous','html', $h$<p>This Agreement is the entire agreement between you and the Company regarding its subject matter and supersedes prior discussions on that subject; it does not replace or modify your contract with the Venue. Any amendment must be in a writing signed by both parties. If any provision is held unenforceable, it will be modified to the minimum extent necessary or severed, and the remainder will remain in effect. A failure to enforce a provision is not a waiver. This Agreement may be signed in counterparts and by electronic signature, each of which is deemed an original.</p>$h$),
      jsonb_build_object('id','s17','type','section','title','17. Acknowledgment','html', $h$<p>By signing below, you confirm that you have read and understood this Agreement, that you have had the opportunity to ask questions and to consult an attorney of your choosing, and that you sign voluntarily. You acknowledge that the Company’s willingness to perform at the Event is made in reliance on this Agreement.</p>$h$),
      jsonb_build_object('id','sign','type','signature')
    ))
  returning id into v_tpl;

  update journey_types
    set agreement_template_id = v_tpl,
        calendar_embed = $embed$<iframe src="https://api.leadconnectorhq.com/widget/booking/cPllfYSeHEB1DRTsraIK" style="width: 100%;border:none;overflow: hidden;" scrolling="no" id="cPllfYSeHEB1DRTsraIK_1784306266630"></iframe><br><script src="https://link.msgsndr.com/js/form_embed.js" type="text/javascript"></script>$embed$
    where name = 'Venue Partner';
end $mig$;
